


--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) Total_Revenue from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount from customer
where discount_applied = 'yes' and purchase_amount > (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased from customer
where review_rating > (select AVG(review_rating) from customer)

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,round(AVG(purchase_amount),2) from customer
where shipping_type in ('Express','Free Shipping')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
AVG(purchase_amount) Avg_purchase_amount,
sum(purchase_amount) Total_revenue 
	from customer
	where subscription_status in('Yes','No')
	group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 Item_purchased,
							round(100.0 * sum(case when discount_applied = 'yes' then 1 else 0 end )/count(*),2) as Discount_percentage 
			from customer
			group by Item_purchased 
			ORDER BY Discount_percentage DESC



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with cte as (
select customer_id,previous_purchases,
					case 
						 when previous_purchases = 1 then 'New' 
						 when previous_purchases  between 2 and 10 then 'Returning' 
						 else 'Loyal' end as Segment
			
from customer
) 
select Segment,count(*) as 'Number of Customers' from cte 
group by Segment


--Q8. What are the top 3 most purchased products within each category? 
--select distinct category from customer

with cte as (
select category,
	  item_purchased,
	  count(customer_id) 'Total orders',
	  ROW_NUMBER() over (partition by category order by count(customer_id) desc) as rnk 
from customer
group by category,item_purchased
)
select * from cte 
where rnk <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 

select age_group,
	   sum(purchase_amount) 'Revenue_contribution' 
from customer 
group by age_group
order by Revenue_contribution desc


